<a href="https://colab.research.google.com/github/hiiambobby/Basic-Front-End/blob/main/LA_PHW2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra Practical Homework 2:

The following assignment consists of:
1. Implementation of elementary row operations : Scaling, Replacement, Interchange
2. Using the defined functions to find the answer of a system
3. Calculation of the determinant
4. EXTRA - Plotting the answer

TAs in charge: @ayrozz , @alijahan890

Please fill in the following information:

- Student: [Saba Seyed tabaei]
- Student ID: [40123042]

# How to complete this notebook?
To complete this notebook you just need to change the parts of code that is marked by comment `#CHNAGE THIS PART`. Please do not change cells that contains comment `# DO NOT CHANGE THIS CELL`. These cells are for evaluating your implementation.

# Attention!
 - You are free to add, remove or edit each cell in any way you desire.
 - We strongly recommend you to observe the default order of different parts of this file.
 - NO PREDEFINED BUILT-IN FUNCTION OF EXTERNAL LIBRARIES SUCH AS NUMPY IS ALLOWED!

### 0. Libraries

In [49]:
import time
import matplotlib
import numpy as np

## 1. Implementation of elementary row operations
Implement these operations from scratch, for they will be used for upcoming sections


### 1.1. Scaling

In [70]:
def op_scale(A, R, C):
    #CHNAGE THIS PART
    """ Multiply the R-th row of the matrix A by C, and return the new matrix """
    R -= 1
    A[R] *= C
    print(A)

In [71]:
#e.g.
# DO NOT CHANGE THIS CELL
A = np.array([[10, 3, 2, 1],
               [ 1, 0, 4, 2],
               [ 7, 5,-1, 9],
               [-6,-7, 8,-4]])

op_scale(A, 2, 3)


"""
 Expected_output = [[10, 3, 2, 1],
                    [ 3, 0,12, 6],
                    [ 7, 5,-1, 9],
                    [-6,-7, 8,-4]]
"""


[[10  3  2  1]
 [ 3  0 12  6]
 [ 7  5 -1  9]
 [-6 -7  8 -4]]


'\n Expected_output = [[10, 3, 2, 1],\n                    [ 3, 0,12, 6],\n                    [ 7, 5,-1, 9],\n                    [-6,-7, 8,-4]]\n'

### 1.2. Interchange

In [73]:
def op_interchange(A, R1, R2):
    #CHNAGE THIS PART
    """ Replace R1-th and R2-th rows in the matrix A, and return the new matrix """
    R1 = R1 - 1
    R2 = R2 - 1
    A[[R1,R2]] = A[[R2,R1]]
    print(A)



In [74]:
# e.g.
# DO NOT CHANGE THIS CELL
op_interchange(A, 3, 4)
"""
Expected_output = [[10, 3, 2, 1],
                    [ 3, 0,12, 6],
                    [-6,-7, 8,-4],
                    [ 7, 5,-1, 9]]
"""

[[10  3  2  1]
 [ 3  0 12  6]
 [-6 -7  8 -4]
 [ 7  5 -1  9]]


'\nExpected_output = [[10, 3, 2, 1],\n                    [ 3, 0,12, 6],\n                    [-6,-7, 8,-4],\n                    [ 7, 5,-1, 9]]\n'

### 1.3. Replace

In [75]:
def op_replace(A, R1, R2 , C):
    #CHNAGE THIS PART
    """ Replace the R2-th row with (R2 + C*R1), and return the new matrix """
    R2 -= 1
    R1 -= 1
    A[R2] = A[R2] + A[R1] * C
    print(A)


In [76]:
# e.g.
# DO NOT CHANGE THIS CELL
op_replace(A, 2, 1, 4)
"""
Expected_output = [[22, 3,50,25],
                   [ 3, 0,12, 6],
                   [-6,-7, 8,-4],
                   [ 7, 5,-1, 9]]
"""


[[22  3 50 25]
 [ 3  0 12  6]
 [-6 -7  8 -4]
 [ 7  5 -1  9]]


'\nExpected_output = [[22, 3,50,25],\n                   [ 3, 0,12, 6],\n                   [-6,-7, 8,-4],\n                   [ 7, 5,-1, 9]]\n'

## 2. Solving a system of linear equations
In this part, you are required to use the functions defined in the previous part to find the solution to a linear system of equations.


### 2.1. Row Echelon Form

In [ ]:
def row_echelon(A):
    #CHNAGE THIS PART
    """ Define an algorithm to find the row-echelon form of the input matrix, row-echelon form of a matrix is not unique, so any true row-echelon form is acceptable."""

In [ ]:
#e.g.
# DO NOT CHANGE THIS CELL
B = np.array([[ 1, 2, 3, 4],
              [ 5, 6, 7, 8],
              [ 9,10,11,12]])
row_echelon(B)
""""
Notice that any true row-echelon form is acceptable. An example is given below:
([[ 1, 2, 3, 4],
  [ 0,-4,-8,-12],
  [ 0, 0, 0, 0]])
"""


### 2.2. Reduce Row Echelon Form

In [ ]:
def reduce(A):
    #CHNAGE THIS PART
    """ Define an algorithm to find the reduced-row-echelon form of the input matrix
        ATTENTION : Assume  the input matrix is already in row-echelon form!"""

In [ ]:
# e.g.
# DO NOT CHANGE THIS CELL
B = np.array([[ 1, 2, 3, 4],
              [ 0,-4,-8,-12],
              [ 0, 0, 0, 0]])
reduce(B)
"""
Expected_output = [[ 1, 0,-1,-2],
                   [ 0, 1, 2, 3],
                   [ 0, 0, 0, 0]]
"""

### 2.3. Existence of the Solution
Based on the reduced form of the augmented matrix and prior to finding the answer, make sure the solution exists!

In [ ]:
def is_consistent(A):
    #CHNAGE THIS PART
    """ Make sure the system has a solution or not """

In [ ]:
#e.g.
# DO NOT CHANGE THIS CELL
is_consistent(B)
"""
expected_output: true
"""

### 2.4. Uniqueness of the Solution
Based on prior information, make sure whether the solution is unique or not!

In [ ]:
def is_unique(A):
    #CHNAGE THIS PART
    """ Address the uniqueness of solution """

In [ ]:
#e.g.
# DO NOT CHANGE THIS CELL
is_unique(B)
"""
expected_output: false
"""

### 2.5. Finding (just a) Solution
If the system has a solution, find and return it.
If the system has infinite solutions, return only one solution and double-check it with the original system defintion.

In [ ]:
def solve(A):
    #CHNAGE THIS PART
    """ Find the solution, A is the augmented matrix """

## 3. Determinant
In this section, you are requiered to find the determinant of a matrix in two different ways and compare them in the sense of computation complexity.


### 3.1. Recursive algorithm
Implement a recursive algorithm to compute the determinant of a N*N matrix, using expansion with respect to a column or a row.


In [ ]:
def det_recursive(A):
    #CHNAGE THIS PART
    """ Find the determinant of the matrix A, make sure it is a square matrix and raise an error otherwise """

In [ ]:
#e.g.
# DO NOT CHANGE THIS CELL
Matrix = np.array([[ 5, 7,-2, 1],
                   [-1, 5,-3, 0],
                   [ 3,11,-2,-9],
                   [ 8, 0, 4,-1]])
print(det_recursive(Matrix))
"""
expected_output = 190
"""

#### 3.1.1. Test your algorithm
Measure the computation time of you recursive algorithm by testing it N*N matrixes, N= 2, 3, 4, 5, 6, 7

In [ ]:
# Testing
M2 = [[4,5],[2,3]]
M3 = [[3,2,1],[2,2,2],[0,3,1]]
# M4 =
# define the rest of the matrixes up to 7*7, you may use random number generators

elapsed_time_recursive=[0]*6

start_time = time.time()
d1 = det_recursive(M2)
end_time = time.time()
elapsed_time_recursive[0] = end_time - start_time
print("Time Elapsed for recursive computation of determinant of M2 : " , elapsed_time_recursive[0])

# Do the same for the rest of the matrices up to 7*7


### 3.2. Row Echelon
Use the function defined in part 1 to find the row echelon form of the matrix and calculate the determinant

#### ATTENTION: BEWARE OF THE IMPACT OF EACH OPERATION ON THE DETERMINANT!

In [ ]:
def det_row_echelon(A):
    #CHNAGE THIS PART
    """ Find the determinant of the matrix A, make sure it is a square matrix and raise error otherwise """

#### 3.2.1 Test your algorithm
Measure the computation time of you recursive algorithm by testing it on the matrixes defined in the previous section.

In [ ]:
# Testing
elapsed_time_rowechelon=[0]*6

start_time = time.time()
d1 = det_row_echelon(M2)
end_time= time.time()
elapsed_time_rowechelon[0] = end_time - start_time

print("Time Elapsed for recursive computation of determinant of M2 : " , elapsed_time_rowechelon[0])

# Do the same for the rest of the matrices up to 7*7

### 3.3. Compare the computation time of the two proposed methods
Try to plot the computation time versus matrix size for both methods using matplotlib functions.

In [ ]:
# Plot the recorded data

## 4. EXTRA - 2D and 3D plotting
In this part, you are demanded to solve two underdetermined systems of size N=2 and N=3 and plot the hyperplane of the results using matplotlib.
For example if a 2*2 system in underdetermined (has infinitely many solutions), the solution space is the span of a vector set consisting of one 2-dimentional vector, thus it can be plotted as a line in the 2D space.

Solving this part will provide you with extra points.

In [ ]:
# Plot the solution set